version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ajay
      MONGO_INITDB_ROOT_PASSWORD: ajay
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: deeplab
    ports:
      - "3100:3100"
    depends_on:
      - mongo
    environment:
      - MONGO_DB=mongodb+srv://ajay:ajay@deeplab.fc3g6eb.mongodb.net/?retryWrites=true&w=majority&appName=deeplab

volumes:
  mongo-data:
